name: Hexo预编译静态文件
on:
  push:
    branches: [ source ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Node20环境
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - name: 安装依赖并编译
        run: |
          npm ci
          NODE_OPTIONS="--max-old-space-size=2048" npx hexo generate
      - name: 部署到gh-pages分支
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages